#!/usr/bin/env bash
printf "\tdocker aliases\n"

# -- Docker --------------------------------------------------------------------
alias docker-machine='__docker_machine_wrapper'
alias di='docker images'
alias 'docker.ssh'='docker-machine ssh default'  # or, alias 'ssh.docker'="echo 'password is \`tcuser\`'; ssh docker@$(docker-machine ip default)"
alias 'docker.ls'="docker ps --format 'table {{.ID}}\t{{.Image}}\t{{.Status}}\t{{.Names}}\t{{.Ports}}'"

alias 'docker.psql.start'='docker run --name postgres -p 5432:5432 --detach kiasaki/alpine-postgres:11.5'
alias 'docker.psql.stop'='docker rm postgres'

alias 'docker.stop.all'='docker_stop_all'
alias 'docker.stop.self'='docker_stop_container'
alias 'docker.rmi.all'='docker_remove_images_all'
alias 'docker.rmi.self'='docker_remove_image'


# -- Custom Applicationtions ---------------------------------------------------
alias dchef='docker run -ti -v $(pwd):/builder -v /var/run/docker.sock:/var/run/docker.sock iamjohnnym/dockerstation chef exec bundle install ; chef exec '
