#!/usr/bin/env bash
printf "\tvscode bashrc\n"

# shellcheck disable=2154
cmp ~/Library/Application\ Support/Code/User/settings.json \
    "${DOTFILE_PATH}/lib/vscode/user_settings.json" || \
    mv ~/Library/Application\ Support/Code/User/settings.json{,.bak-"$_now"} ;
    cp "${DOTFILE_PATH}/lib/vscode/user_settings.json" \
    ~/Library/Application\ Support/Code/User/settings.json
