#!/usr/bin/env bash
printf "\tbrew bashrc\n"

HOMEBREW_PREFIX=$(brew --prefix)
if type brew &>/dev/null; then
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
    # shellcheck source=/dev/null
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
      # shellcheck source=/dev/null
      [[ -r "$COMPLETION" ]] && source "$COMPLETION"
    done
  fi
fi

# -- Homebrew ------------------------------------------------------------------
HOMEBREW_DIR=/usr/local/Homebrew
export PATH=$HOMEBREW_DIR/bin:$HOMEBREW_DIR/sbin:$PATH
export MANPATH=$HOMEBREW_DIR/share/man:$MANPATH
export HOMEBREW_NO_ANALYTICS=1

#BREW_CHECK=$(brew bundle check)

#if $? -ne 0 ; then
#  echo "Brew updates are pending..."
#  echo "$BREW_CHECK"
#fi
