#!/usr/bin/env bash
printf "\tbashrc\n"

declare -a _now=("$(date +%m_%d_%Y)")
export _now

# general
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export EDITOR=vim
export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/sbin:$PATH"

function fuck() {
  if killall -9 "$2"; then
    echo ; echo " (╯°□°）╯︵$(echo "$2"|toilet -f term -F rotate)"; echo
  fi
}
